version: "3"

includes:
  dotto_design_system:
    taskfile: ./dotto_design_system/Taskfile.yml
    dir: ./dotto_design_system
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api

vars:
  FLUTTER: flutter
  DART: dart
  FASTLANE: fastlane

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  install:
    desc: Install dependencies and configure Flutter
    cmds:
      - "{{.FLUTTER}} config --enable-swift-package-manager"
      - "{{.FLUTTER}} pub get"
      - "mise install"
      - "pre-commit install"

  install-all:
    desc: Install dependencies for all projects
    deps:
      - task: install
        vars:
          FLUTTER: "{{.FLUTTER}}"
      - task: dotto_design_system:install
        vars:
          FLUTTER: "{{.FLUTTER}}"
      - task: api:install
        vars:
          FLUTTER: "{{.FLUTTER}}"

  generate-openapi:
    desc: Generate OpenAPI code
    cmds:
      - openapi-generator generate -i ./openapi/openapi.yaml -g dart-dio -o ./api

  build:
    desc: Run build_runner to generate code
    cmds:
      - "{{.DART}} run build_runner build --delete-conflicting-outputs"

  build-all:
    desc: Run build_runner to generate code for all projects
    deps:
      - task: build
        vars:
          DART: "{{.DART}}"
      - task: dotto_design_system:build
        vars:
          DART: "{{.DART}}"
      - task: api:build
        vars:
          DART: "{{.DART}}"

  watch:
    desc: Run build_runner to generate code in watch mode
    cmds:
      - "{{.DART}} run build_runner watch --delete-conflicting-outputs"

  watch-all:
    desc: Run build_runner to generate code in watch mode for all projects
    deps:
      - task: watch
        vars:
          DART: "{{.DART}}"
      - task: dotto_design_system:watch
        vars:
          DART: "{{.DART}}"
      - task: api:watch
        vars:
          DART: "{{.DART}}"

  run:
    desc: Run the Flutter app
    cmds:
      - "dotenvx decrypt --stdout > .env.decrypted && {{.FLUTTER}} run --dart-define-from-file=.env.decrypted; rm -f .env.decrypted"

  run-storybook:
    desc: Run the Storybook app
    cmds:
      - task: dotto_design_system:run
        vars:
          FLUTTER: "{{.FLUTTER}}"

  clean:
    desc: Clean Flutter build files
    cmds:
      - "{{.FLUTTER}} clean"

  test:
    desc: Run Flutter tests
    cmds:
      - "{{.FLUTTER}} test"

  test-with-coverage:
    desc: Run Flutter tests with coverage report
    cmds:
      - "{{.FLUTTER}} test --coverage"
      - task: build-coverage-report

  build-coverage-report:
    desc: Build coverage report
    cmds:
      - "lcov --remove coverage/lcov.info 'lib/**.g.dart' -o coverage/new_lcov.info --ignore-errors unused"
      - "genhtml coverage/new_lcov.info -o coverage/html"
      - "open coverage/html/index.html"

  analyze:
    desc: Analyze Dart code
    cmds:
      - task install
      - task build
      - "{{.FLUTTER}} analyze ./lib/ ./test/"

  build-ios:
    desc: Build iOS release
    cmds:
      - task: build
      - "dotenvx decrypt --stdout > .env.decrypted && {{.FLUTTER}} build ios --release --dart-define-from-file=.env.decrypted; rm -f .env.decrypted"

  build-android:
    desc: Build Android release appbundle
    cmds:
      - task: build
      - "dotenvx decrypt --stdout > .env.decrypted && {{.FLUTTER}} build appbundle --release --dart-define-from-file=.env.decrypted; rm -f .env.decrypted"

  deploy-ios-firebase-app-distribution:
    desc: Deploy iOS to Firebase App Distribution
    dir: ./ios
    cmds:
      - "{{.FASTLANE}} deploy_firebase_app_distribution"

  deploy-android-firebase-app-distribution:
    desc: Deploy Android to Firebase App Distribution
    dir: ./android
    cmds:
      - "{{.FASTLANE}} deploy_firebase_app_distribution"

  deploy-ios-testflight:
    desc: Deploy iOS to TestFlight
    dir: ./ios
    cmds:
      - "{{.FASTLANE}} deploy_testflight"

  deploy-android-google-play:
    desc: Deploy Android to Google Play
    dir: ./android
    cmds:
      - "{{.FASTLANE}} deploy_google_play"

  match-development:
    desc: Match development certificates (readonly)
    dir: ./ios
    cmds:
      - "{{.FASTLANE}} match_development_readonly"

  bump-build:
    desc: Bump build number
    cmds:
      - "{{.DART}} pub global activate pub_version_plus"
      - "{{.DART}} pub global run pub_version_plus:main build"

  bump-patch:
    desc: Bump patch version and reset build number
    cmds:
      - "{{.DART}} pub global activate pub_version_plus"
      - "{{.DART}} pub global run pub_version_plus:main patch --build reset"

  bump-minor:
    desc: Bump minor version and reset build number
    cmds:
      - "{{.DART}} pub global activate pub_version_plus"
      - "{{.DART}} pub global run pub_version_plus:main minor --build reset"

  bump-major:
    desc: Bump major version and reset build number
    cmds:
      - "{{.DART}} pub global activate pub_version_plus"
      - "{{.DART}} pub global run pub_version_plus:main major --build reset"

  register-ios-device:
    desc: Register iOS device and update provisioning profiles
    dir: ./ios
    vars:
      NAME: "{{.name}}"
      UDID: "{{.udid}}"
    cmds:
      - "{{.FASTLANE}} run register_device name:{{.NAME}} udid:{{.UDID}}"
      - "{{.FASTLANE}} match_development"
      - "{{.FASTLANE}} match_adhoc"
      - "{{.FASTLANE}} match_appstore"
